export const CHANNEL_RECEIVED = "CHANNEL_RECEIVED";
export const ADD_CHANNEL_RECEIVED = "ADD_CHANNEL_RECEIVED";
export const CHANNEL_FAILURE = "CHANNEL_FAILURE";
export const CHANNEL_REQUEST = "CHANNEL_REQUEST";
