export const ADD_CHANNEL_BEGIN = "ADD_CHANNEL_BEGIN";
export const ADD_CHANNEL_SUCCESS = "ADD_CHANNEL_SUCCESS";
export const ADD_CHANNEL_FAILURE = "ADD_CHANNEL_FAILURE";
export const FETCH_CHANNEL = "FETCH_CHANNEL";
