export const MESSAGES_REQUEST = 'MESSAGES_REQUEST';
export const MESSAGES_RECEIVED = 'MESSAGES_RECEIVED';
export const MESSAGES_FAILURE = 'MESSAGES_FAILURE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_RECEIVED = 'ADD_MESSAGE_RECEIVED'