export const USER_REQUEST = "USER_REQUEST";
export const LOGIN_USER_RECEIVED = "LOGIN_USER_RECEIVED";
export const LOGOUT_USER_RECEIVED = "LOGOUT_USER_RECEIVED";
export const CREATE_USER_RECEIVED = "CREATE_USER_RECEIVED";
export const USER_FAILURE = "USER_FAILURE";
